# F2_01 Obtención

Este notebook corresponde al orquestador de la fase F2 de la ingeniía de datos. Llama en orden a las funciones definidas en F2/src/:

1. `extraer_votaciones` (01) — cataloga las votaciones del proyecto de ley
2. `extraer_periodos` (02) — resuelve los períodos legislativos
3. `extraer_diputados` (03) — extrae diputados y militancias por período
4. `extraer_detalles_votaciones` (04) — extrae el detalle nominal de cada votación

Cada función guarda su propio resultado en `data/raw/` y `data/interim/`.
Este notebook no reimplementa lógica: solo orquesta el orden de ejecución.

## Conifiguración de imports

In [14]:
import pandas as pd
import sys
from pathlib import Path

# F2/notebooks/ y F2/src/ son carpetas hermanas dentro de F2/;
# agregamos F2/src al path para poder importar los módulos.
SRC_DIR = Path.cwd().parent / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

In [3]:
from importlib import import_module

extraer_votaciones = import_module("01_extraer_votaciones_proyecto").extraer_votaciones
extraer_periodos = import_module("02_periodos_legislativos").extraer_periodos
extraer_diputados = import_module("03_diputados").extraer_diputados
extraer_detalles_votaciones = import_module("04_extraer_detalles_votaciones").extraer_detalles_votaciones

## 01 · Catalogar votaciones

Consulta `retornarVotacionesXProyectoLey` para el boletín del proyecto de ley
sobre protección de datos personales (11092-07).

In [16]:
NUMERO_BOLETIN = "11092-07"

df_votaciones = extraer_votaciones(NUMERO_BOLETIN)
df_votaciones

Consultando boletín: 11092-07
XML guardado en: /Users/ygallardo/Documents/Magister UNAB/Programacion para la cienia de datos/grupo_1_programacion_ciencia_datos/F2/data/raw/VotacionesPorProyectoDeLey/proyecto_ley.xml
CSV guardado en: /Users/ygallardo/Documents/Magister UNAB/Programacion para la cienia de datos/grupo_1_programacion_ciencia_datos/F2/data/interim/VotacionesPorProyectoDeLey/proyecto_ley.csv
Registros extraídos: 15

,numero_boletin,Id,Descripcion,Fecha,TotalSi,TotalNo,TotalAbstencion,TotalDispensado,Quorum,Resultado,Tipo,TipoVotacionProyectoLey,Articulo,TramiteConstitucional,TramiteReglamentario
0,11092-07,42724,Boletín N°11092-07,2024-08-26T19:03:25,65,22,36,0,Quórum Calificado,Aprobado,Proyecto de Ley,Única,Proposición de la Comisión Mixta recaída en el...,Comisión Mixta,Sin Informe
1,11092-07,21219,Boletín N°11092-07,2023-05-08T19:18:45,74,59,2,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Letra c) del artículo 35, contenido en el nume...",Segundo Trámite,Primer Informe
2,11092-07,21218,Boletín N°11092-07,2023-05-08T19:17:43,73,60,2,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Letra b) del artículo 35, contenido en el nume...",Segundo Trámite,Primer Informe
3,11092-07,21217,Boletín N°11092-07,2023-05-08T19:16:53,90,38,7,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Artículo 32, contenido en el numeral 12) del a...",Segundo Trámite,Primer Informe
4,11092-07,20637,Boletín N°11092-07,2023-05-08T19:15:59,91,41,3,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Artículo 31, contenido en el numeral 12) del a...",Segundo Trámite,Primer Informe
5,11092-07,20636,Boletín N°11092-07,2023-05-08T19:15:04,92,40,3,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Artículo 30 nonies, contenido en el numeral 12...",Segundo Trámite,Primer Informe
6,11092-07,20635,Boletín N°11092-07,2023-05-08T19:13:51,92,40,3,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Artículo 30 octies, contenido en el numeral 12...",Segundo Trámite,Primer Informe
7,11092-07,20634,Boletín N°11092-07,2023-05-08T19:12:58,94,40,1,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Artículo 30 quáter, contenido en el numeral 12...",Segundo Trámite,Primer Informe
8,11092-07,20633,Boletín N°11092-07,2023-05-08T19:11:56,94,39,2,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Artículo 30 ter, contenido en el numeral 12) d...",Segundo Trámite,Primer Informe
9,11092-07,20632,Boletín N°11092-07,2023-05-08T19:11:06,93,42,0,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Artículo 30 bis, contenido en el numeral 12) d...",Segundo Trámite,Primer Informe
10,11092-07,20631,Boletín N°11092-07,2023-05-08T19:10:13,91,43,1,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Artículo 30, contenido en el numeral 12) del a...",Segundo Trámite,Primer Informe
11,11092-07,20630,Boletín N°11092-07,2023-05-08T19:09:23,90,40,5,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Letra L) del artículo 14 ter, contenido en el ...",Segundo Trámite,Primer Informe
12,11092-07,20629,Boletín N°11092-07,2023-05-08T19:08:21,90,42,3,0,Quórum Simple,Aprobado,Proyecto de Ley,Particular,"Encabezado del artículo 14 ter, contenido en e...",Segundo Trámite,Primer Informe
13,11092-07,20628,Boletín N°11092-07,2023-05-08T19:06:49,128,0,0,0,Quórum Calificado,Aprobado,Proyecto de Ley,General,"Letra h) del artículo 3°, contenido en el nume...",Segundo Trámite,Primer Informe
14,11092-07,20627,Boletín N°11092-07,2023-05-08T19:05:22,122,0,0,0,Quórum Simple,Aprobado,Proyecto de Ley,General,NaN,Segundo Trámite,Primer Informe

## 02 · Resolver períodos

Consulta `retornarPeriodosLegislativos` (sin parámetros, trae todos los
períodos disponibles) y guarda `periodos.csv`.

In [ ]:
extraer_periodos()

Guardado en: /Users/ygallardo/Documents/Magister UNAB/Programacion para la cienia de datos/grupo_1_programacion_ciencia_datos/F2/data/interim/periodos.csv (11 filas)

In [15]:
df_periodos = pd.read_csv(Path.cwd().parent / "data" / "interim" / "periodos.csv")
df_periodos

    periodo_id     nombre fecha_inicio        fecha_termino
0            7  1965-1969   1965-03-11  1969-03-11 00:00:00
1            1  1990-1994   1990-03-11  1994-03-10 00:00:00
2            2  1994-1998   1994-03-11  1998-03-10 00:00:00
3            3  1998-2002   1998-03-11  2002-03-10 00:00:00
4            4  2002-2006   2002-03-11  2006-03-10 00:00:00
5            5  2006-2010   2006-03-11  2010-03-10 00:00:00
6            6  2010-2014   2010-03-11  2014-03-10 00:00:00
7            8  2014-2018   2014-03-11  2018-03-10 23:59:59
8            9  2018-2022   2018-03-11  2022-03-10 23:59:59
9           10  2022-2026   2022-03-11  2026-03-10 23:59:59
10          11  2026-2030   2026-03-11  2030-03-10 23:59:59

## 03 · Extraer diputados

Primero se busca el periodo correspondiente a cada votación y luego se integra en una variable para la consulta `retornarDiputadosXPeriodo` para el período legislativo vigente

In [17]:
def buscar_periodo(fecha_votacion, df_periodos):
    inicios = pd.to_datetime(df_periodos["fecha_inicio"])
    terminos = pd.to_datetime(df_periodos["fecha_termino"])
    vigente = df_periodos[(inicios <= fecha_votacion) & (fecha_votacion <= terminos)]
    if vigente.empty:
        return None
    return vigente.iloc[0]["periodo_id"]

fechas_votacion = pd.to_datetime(df_votaciones["Fecha"])
df_votaciones["periodo_id"] = fechas_votacion.apply(lambda f: buscar_periodo(f, df_periodos))

df_votaciones[["Id", "Fecha", "periodo_id"]]

       Id                Fecha  periodo_id
0   42724  2024-08-26T19:03:25          10
1   21219  2023-05-08T19:18:45          10
2   21218  2023-05-08T19:17:43          10
3   21217  2023-05-08T19:16:53          10
4   20637  2023-05-08T19:15:59          10
5   20636  2023-05-08T19:15:04          10
6   20635  2023-05-08T19:13:51          10
7   20634  2023-05-08T19:12:58          10
8   20633  2023-05-08T19:11:56          10
9   20632  2023-05-08T19:11:06          10
10  20631  2023-05-08T19:10:13          10
11  20630  2023-05-08T19:09:23          10
12  20629  2023-05-08T19:08:21          10
13  20628  2023-05-08T19:06:49          10
14  20627  2023-05-08T19:05:22          10

In [19]:
PERIODO_ID = df_votaciones["periodo_id"].iloc[0]
print(PERIODO_ID)

10

In [20]:
extraer_diputados(PERIODO_ID)

Guardado en: /Users/ygallardo/Documents/Magister UNAB/Programacion para la cienia de datos/grupo_1_programacion_ciencia_datos/F2/data/raw/diputados/diputados_periodo_10.xml
Guardado en: /Users/ygallardo/Documents/Magister UNAB/Programacion para la cienia de datos/grupo_1_programacion_ciencia_datos/F2/data/interim/diputados.csv (157 filas)
Guardado en: /Users/ygallardo/Documents/Magister UNAB/Programacion para la cienia de datos/grupo_1_programacion_ciencia_datos/F2/data/interim/militancias.csv (407 filas)

## Revisión de CSV de diputados y militancia

Se revisan los csv generados a partir de extraer_diputados

In [23]:
df_diputados = pd.read_csv(Path.cwd().parent / "data" / "interim" / "diputados.csv")
df_diputados.head()

,diputado_id,nombre,nombre2,apellido_paterno,apellido_materno,fecha_nacimiento,rut,rut_dv,sexo,periodo_id,fecha_inicio_periodo,fecha_termino_periodo
0,1096,María Candelaria,NaN,Acevedo,Sáez,1958-09-12 00:00:00,NaN,NaN,"{\n '_value_1': 'Femenino',\n 'Valor': 0\n}",10,2026-03-10 23:59:59,NaN
1,1097,Eric,NaN,Aedo,Jeldres,1968-07-13 00:00:00,NaN,NaN,"{\n '_value_1': 'Masculino',\n 'Valor': ...",10,2026-03-10 23:59:59,NaN
2,1098,Yovana,NaN,Ahumada,Palma,1973-02-24 00:00:00,NaN,NaN,"{\n '_value_1': 'Femenino',\n 'Valor': 0\n}",10,2026-03-10 23:59:59,NaN
3,1009,Jorge,NaN,Alessandri,Vergara,1979-06-08 00:00:00,NaN,NaN,"{\n '_value_1': 'Masculino',\n 'Valor': ...",10,2026-03-10 23:59:59,NaN
4,803,René,NaN,Alinco,Bustos,1958-06-02 00:00:00,NaN,NaN,"{\n '_value_1': 'Masculino',\n 'Valor': ...",10,2026-03-10 23:59:59,NaN

In [24]:
df_militancias = pd.read_csv(Path.cwd().parent / "data" / "interim" / "militancias.csv")
df_militancias.head()

,diputado_id,partido_id,partido_nombre,partido_alias,fecha_inicio,fecha_termino
0,1096,PC,Partido Comunista,PC,2022-03-11 00:00:00,2026-03-10 23:59:59
1,1097,DC,Partido Demócrata Cristiano,DC,2022-03-11 00:00:00,2026-03-10 23:59:59
2,1098,PDG,Partido de la Gente,PDG,2022-03-11 00:00:00,2023-04-18 23:59:59
3,1098,IND,Independientes,IND,2023-04-19 00:00:00,2025-03-16 23:59:59
4,1098,PSC,Partido Social Cristiano,PSC,2025-03-17 00:00:00,2026-03-10 23:59:59

## 04 · Extraer detalles de votación

Lee los identificadores de votación generados en el paso 01
(`proyecto_ley.csv`) y descarga el detalle nominal de cada una.

In [7]:
df_detalles = extraer_detalles_votaciones()
df_detalles.head()

Votaciones encontradas: 15
[1/15] Descargando votación 42724
[2/15] Descargando votación 21219
[3/15] Descargando votación 21218
[4/15] Descargando votación 21217
[5/15] Descargando votación 20637
[6/15] Descargando votación 20636
[7/15] Descargando votación 20635
[8/15] Descargando votación 20634
[9/15] Descargando votación 20633
[10/15] Descargando votación 20632
[11/15] Descargando votación 20631
[12/15] Descargando votación 20630
[13/15] Descargando votación 20629
[14/15] Descargando votación 20628
[15/15] Descargando votación 20627
Leyendo votacion_42724.xml
Leyendo votacion_21219.xml
Leyendo votacion_21218.xml
Leyendo votacion_21217.xml
Leyendo votacion_20637.xml
Leyendo votacion_20636.xml
Leyendo votacion_20635.xml
Leyendo votacion_20634.xml
Leyendo votacion_20633.xml
Leyendo votacion_20632.xml
Leyendo votacion_20631.xml
Leyendo votacion_20630.xml
Leyendo votacion_20629.xml
Leyendo votacion_20628.xml
Leyendo votacion_20627.xml
CSV generado: /Users/ygallardo/Documents/Magister UNAB/Programacion para la cienia de datos/grupo_1_programacion_ciencia_datos/F2/data/interim/votaciones/detalle_votaciones.csv
Registros obtenidos: 1993

,diputado_id,nombre,nombre2,apellido_paterno,apellido_materno,opcion_codigo,opcion_voto,votacion_id,descripcion,fecha,total_si,total_no,total_abstencion,total_dispensado,quorum_codigo,quorum,resultado_codigo,resultado,tipo_codigo,tipo
0,803,René,None,Alinco,Bustos,0,En Contra,42724,Boletín N° 11092-07,2024-08-26T19:03:25,65,22,36,0,2,Quórum Calificado,1,Aprobado,1,Proyecto de Ley
1,815,Sergio,None,Bobadilla,Muñoz,2,Abstención,42724,Boletín N° 11092-07,2024-08-26T19:03:25,65,22,36,0,2,Quórum Calificado,1,Aprobado,1,Proyecto de Ley
2,872,Jaime,None,Mulet,Martínez,1,Afirmativo,42724,Boletín N° 11092-07,2024-08-26T19:03:25,65,22,36,0,2,Quórum Calificado,1,Aprobado,1,Proyecto de Ley
3,917,Gastón,None,Von Mühlenbrock,Zamora,0,En Contra,42724,Boletín N° 11092-07,2024-08-26T19:03:25,65,22,36,0,2,Quórum Calificado,1,Aprobado,1,Proyecto de Ley
4,948,Gaspar,None,Rivas,Sánchez,2,Abstención,42724,Boletín N° 11092-07,2024-08-26T19:03:25,65,22,36,0,2,Quórum Calificado,1,Aprobado,1,Proyecto de Ley